version: "3.8"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: pentestlab-nginx
    ports:
      - 1000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
  bwapp:
    container_name: pentestlab-bwapp
    image: raesene/bwapp
    platform: linux/amd64
    ports:
      - 1001:80
    networks:
      - pentestlab
    restart: unless-stopped
  dvwa:
    container_name: pentestlab-dvwa
    image: vulnerables/web-dvwa
    platform: linux/amd64
    ports:
      - 1002:80
    networks:
      - pentestlab
    restart: unless-stopped
  homer:
    image: b4bz/homer
    container_name: pentestlab-homer
    volumes:
      - ./homer/assets:/www/assets
    ports:
      - 3000:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=0
networks:
  pentestlab:
    driver: bridge
  homer_default:
    external: true
